// Course Content Structure
// This is the complete syllabus - add your video URLs when ready

import { CourseModule, CourseType } from './types';

export const WEB_COURSE_MODULES: CourseModule[] = [
    {
        id: 'web-m1',
        courseType: 'web',
        moduleNumber: 1,
        title: 'The AI Mindset',
        titleAr: 'عقلية الذكاء الاصطناعي',
        description: 'Set up your environment and learn to think like an AI-powered developer',
        descriptionAr: 'جهّز بيئتك وتعلم أن تفكر كمطور مدعوم بالذكاء الاصطناعي',
        lessons: [
            {
                id: 'web-m1-l1',
                moduleId: 'web-m1',
                lessonNumber: 1,
                title: 'Welcome & Course Overview',
                titleAr: 'مرحباً ونظرة عامة على الدورة',
                description: 'What you will achieve and how this course works',
                descriptionAr: 'ما ستحققه وكيف تعمل هذه الدورة',
                videoUrl: '', // Add your video URL
                videoDuration: 300, // 5 min
            },
            {
                id: 'web-m1-l2',
                moduleId: 'web-m1',
                lessonNumber: 2,
                title: 'Setting Up Cursor IDE',
                titleAr: 'إعداد Cursor IDE',
                description: 'Download and configure the best AI coding tool',
                descriptionAr: 'تحميل وإعداد أفضل أداة برمجة بالذكاء الاصطناعي',
                videoUrl: '',
                videoDuration: 600, // 10 min
                resources: [
                    { id: 'r1', title: 'Cursor Download', type: 'link', url: 'https://cursor.sh' },
                ],
            },
            {
                id: 'web-m1-l3',
                moduleId: 'web-m1',
                lessonNumber: 3,
                title: 'Prompt Engineering Basics',
                titleAr: 'أساسيات هندسة الأوامر',
                description: 'How to talk to AI to get exactly what you want',
                descriptionAr: 'كيف تتحدث مع الذكاء الاصطناعي للحصول على ما تريده بالضبط',
                videoUrl: '',
                videoDuration: 900, // 15 min
            },
            {
                id: 'web-m1-l4',
                moduleId: 'web-m1',
                lessonNumber: 4,
                title: 'Your First AI-Assisted Code',
                titleAr: 'أول كود بمساعدة الذكاء الاصطناعي',
                description: 'Build your first program using only AI prompts',
                descriptionAr: 'ابنِ أول برنامج لك باستخدام أوامر الذكاء الاصطناعي فقط',
                videoUrl: '',
                videoDuration: 720, // 12 min
                challenge: {
                    id: 'c1',
                    title: 'Build a Calculator',
                    description: 'Use AI to create a simple calculator that adds, subtracts, multiplies, and divides',
                },
            },
        ],
    },
    {
        id: 'web-m2',
        courseType: 'web',
        moduleNumber: 2,
        title: 'Zero to One: Your First Website',
        titleAr: 'من الصفر إلى الواحد: موقعك الأول',
        description: 'Build and deploy a professional website in under an hour',
        descriptionAr: 'ابنِ وانشر موقعاً احترافياً في أقل من ساعة',
        lessons: [
            {
                id: 'web-m2-l1',
                moduleId: 'web-m2',
                lessonNumber: 1,
                title: 'HTML Basics with AI',
                titleAr: 'أساسيات HTML مع الذكاء الاصطناعي',
                description: 'Understanding HTML structure - the skeleton of websites',
                descriptionAr: 'فهم بنية HTML - هيكل المواقع',
                videoUrl: '',
                videoDuration: 900,
            },
            {
                id: 'web-m2-l2',
                moduleId: 'web-m2',
                lessonNumber: 2,
                title: 'CSS Styling with AI',
                titleAr: 'تنسيق CSS مع الذكاء الاصطناعي',
                description: 'Make your website beautiful using AI-generated styles',
                descriptionAr: 'اجعل موقعك جميلاً باستخدام أنماط مولّدة بالذكاء الاصطناعي',
                videoUrl: '',
                videoDuration: 1200,
            },
            {
                id: 'web-m2-l3',
                moduleId: 'web-m2',
                lessonNumber: 3,
                title: 'Building a Landing Page',
                titleAr: 'بناء صفحة هبوط',
                description: 'Create a professional landing page from scratch with AI',
                descriptionAr: 'أنشئ صفحة هبوط احترافية من الصفر مع الذكاء الاصطناعي',
                videoUrl: '',
                videoDuration: 1500,
                challenge: {
                    id: 'c2',
                    title: 'Personal Portfolio',
                    description: 'Build your own portfolio website showcasing your skills',
                },
            },
            {
                id: 'web-m2-l4',
                moduleId: 'web-m2',
                lessonNumber: 4,
                title: 'Deploy to the World',
                titleAr: 'انشر للعالم',
                description: 'Put your website online for free using Vercel',
                descriptionAr: 'ضع موقعك على الإنترنت مجاناً باستخدام Vercel',
                videoUrl: '',
                videoDuration: 600,
                resources: [
                    { id: 'r2', title: 'Vercel', type: 'link', url: 'https://vercel.com' },
                ],
            },
        ],
    },
    {
        id: 'web-m3',
        courseType: 'web',
        moduleNumber: 3,
        title: 'JavaScript & Interactivity',
        titleAr: 'JavaScript والتفاعلية',
        description: 'Bring your websites to life with dynamic functionality',
        descriptionAr: 'أضف الحياة لمواقعك مع وظائف ديناميكية',
        lessons: [
            {
                id: 'web-m3-l1',
                moduleId: 'web-m3',
                lessonNumber: 1,
                title: 'JavaScript Fundamentals',
                titleAr: 'أساسيات JavaScript',
                description: 'Variables, functions, and logic - explained simply',
                descriptionAr: 'المتغيرات والدوال والمنطق - شرح بسيط',
                videoUrl: '',
                videoDuration: 1200,
            },
            {
                id: 'web-m3-l2',
                moduleId: 'web-m3',
                lessonNumber: 2,
                title: 'DOM Manipulation',
                titleAr: 'التعامل مع DOM',
                description: 'Make your page respond to user actions',
                descriptionAr: 'اجعل صفحتك تستجيب لأفعال المستخدم',
                videoUrl: '',
                videoDuration: 900,
            },
            {
                id: 'web-m3-l3',
                moduleId: 'web-m3',
                lessonNumber: 3,
                title: 'Building Interactive Components',
                titleAr: 'بناء مكونات تفاعلية',
                description: 'Create modals, dropdowns, and animations',
                descriptionAr: 'أنشئ نوافذ منبثقة وقوائم منسدلة ورسوم متحركة',
                videoUrl: '',
                videoDuration: 1500,
                challenge: {
                    id: 'c3',
                    title: 'Interactive Todo App',
                    description: 'Build a todo list that saves to local storage',
                },
            },
        ],
    },
    {
        id: 'web-m4',
        courseType: 'web',
        moduleNumber: 4,
        title: 'React & Modern Frameworks',
        titleAr: 'React والأطر الحديثة',
        description: 'Build powerful web apps with the industry standard',
        descriptionAr: 'ابنِ تطبيقات ويب قوية مع المعيار الصناعي',
        lessons: [
            {
                id: 'web-m4-l1',
                moduleId: 'web-m4',
                lessonNumber: 1,
                title: 'Why React?',
                titleAr: 'لماذا React؟',
                description: 'Understanding why companies use React',
                descriptionAr: 'فهم لماذا تستخدم الشركات React',
                videoUrl: '',
                videoDuration: 600,
            },
            {
                id: 'web-m4-l2',
                moduleId: 'web-m4',
                lessonNumber: 2,
                title: 'Components & Props',
                titleAr: 'المكونات والخصائص',
                description: 'Building reusable UI pieces',
                descriptionAr: 'بناء قطع واجهة مستخدم قابلة لإعادة الاستخدام',
                videoUrl: '',
                videoDuration: 1200,
            },
            {
                id: 'web-m4-l3',
                moduleId: 'web-m4',
                lessonNumber: 3,
                title: 'State & Effects',
                titleAr: 'الحالة والتأثيرات',
                description: 'Managing data and side effects',
                descriptionAr: 'إدارة البيانات والتأثيرات الجانبية',
                videoUrl: '',
                videoDuration: 1200,
            },
            {
                id: 'web-m4-l4',
                moduleId: 'web-m4',
                lessonNumber: 4,
                title: 'Building a Full React App',
                titleAr: 'بناء تطبيق React كامل',
                description: 'Put it all together in a real project',
                descriptionAr: 'اجمع كل شيء في مشروع حقيقي',
                videoUrl: '',
                videoDuration: 1800,
                challenge: {
                    id: 'c4',
                    title: 'Expense Tracker',
                    description: 'Build an app to track income and expenses',
                },
            },
        ],
    },
    {
        id: 'web-m5',
        courseType: 'web',
        moduleNumber: 5,
        title: 'Monetization & Getting Clients',
        titleAr: 'التسويق والحصول على عملاء',
        description: 'Turn your skills into income',
        descriptionAr: 'حوّل مهاراتك إلى دخل',
        lessons: [
            {
                id: 'web-m5-l1',
                moduleId: 'web-m5',
                lessonNumber: 1,
                title: 'Finding Your First Client',
                titleAr: 'إيجاد عميلك الأول',
                description: 'Where to find clients and how to approach them',
                descriptionAr: 'أين تجد العملاء وكيف تقترب منهم',
                videoUrl: '',
                videoDuration: 1200,
            },
            {
                id: 'web-m5-l2',
                moduleId: 'web-m5',
                lessonNumber: 2,
                title: 'Pricing Your Work',
                titleAr: 'تسعير عملك',
                description: 'How to price projects and negotiate deals',
                descriptionAr: 'كيف تسعّر المشاريع وتفاوض على الصفقات',
                videoUrl: '',
                videoDuration: 900,
            },
            {
                id: 'web-m5-l3',
                moduleId: 'web-m5',
                lessonNumber: 3,
                title: 'Contracts & Invoicing',
                titleAr: 'العقود والفواتير',
                description: 'Protect yourself and get paid',
                descriptionAr: 'احمِ نفسك واحصل على أموالك',
                videoUrl: '',
                videoDuration: 600,
                resources: [
                    { id: 'r3', title: 'Contract Template', type: 'pdf', url: '/resources/contract-template.pdf' },
                    { id: 'r4', title: 'Invoice Template', type: 'pdf', url: '/resources/invoice-template.pdf' },
                ],
            },
        ],
    },
];

export const MOBILE_COURSE_MODULES: CourseModule[] = [
    {
        id: 'mobile-m1',
        courseType: 'mobile',
        moduleNumber: 1,
        title: 'Mobile Development Foundations',
        titleAr: 'أساسيات تطوير الموبايل',
        description: 'Understanding the mobile app landscape',
        descriptionAr: 'فهم مشهد تطبيقات الموبايل',
        lessons: [
            {
                id: 'mobile-m1-l1',
                moduleId: 'mobile-m1',
                lessonNumber: 1,
                title: 'iOS vs Android vs Cross-Platform',
                titleAr: 'iOS مقابل Android مقابل متعدد المنصات',
                description: 'Which approach is right for you?',
                descriptionAr: 'أي نهج مناسب لك؟',
                videoUrl: '',
                videoDuration: 600,
            },
            {
                id: 'mobile-m1-l2',
                moduleId: 'mobile-m1',
                lessonNumber: 2,
                title: 'Setting Up React Native',
                titleAr: 'إعداد React Native',
                description: 'Get your mobile development environment ready',
                descriptionAr: 'جهّز بيئة تطوير الموبايل الخاصة بك',
                videoUrl: '',
                videoDuration: 900,
            },
            {
                id: 'mobile-m1-l3',
                moduleId: 'mobile-m1',
                lessonNumber: 3,
                title: 'Your First Mobile App',
                titleAr: 'تطبيقك الأول للموبايل',
                description: 'Build and run your first app on your phone',
                descriptionAr: 'ابنِ وشغّل أول تطبيق على هاتفك',
                videoUrl: '',
                videoDuration: 1200,
            },
        ],
    },
    {
        id: 'mobile-m2',
        courseType: 'mobile',
        moduleNumber: 2,
        title: 'React Native Deep Dive',
        titleAr: 'الغوص العميق في React Native',
        description: 'Master mobile-specific components and navigation',
        descriptionAr: 'أتقن المكونات الخاصة بالموبايل والتنقل',
        lessons: [
            {
                id: 'mobile-m2-l1',
                moduleId: 'mobile-m2',
                lessonNumber: 1,
                title: 'Mobile UI Components',
                titleAr: 'مكونات واجهة الموبايل',
                description: 'ScrollView, FlatList, and more',
                descriptionAr: 'ScrollView و FlatList والمزيد',
                videoUrl: '',
                videoDuration: 1200,
            },
            {
                id: 'mobile-m2-l2',
                moduleId: 'mobile-m2',
                lessonNumber: 2,
                title: 'Navigation & Screens',
                titleAr: 'التنقل والشاشات',
                description: 'Build multi-screen apps with smooth transitions',
                descriptionAr: 'ابنِ تطبيقات متعددة الشاشات مع انتقالات سلسة',
                videoUrl: '',
                videoDuration: 1500,
            },
            {
                id: 'mobile-m2-l3',
                moduleId: 'mobile-m2',
                lessonNumber: 3,
                title: 'Styling for Mobile',
                titleAr: 'التنسيق للموبايل',
                description: 'Responsive design for all screen sizes',
                descriptionAr: 'تصميم متجاوب لجميع أحجام الشاشات',
                videoUrl: '',
                videoDuration: 900,
            },
        ],
    },
    {
        id: 'mobile-m3',
        courseType: 'mobile',
        moduleNumber: 3,
        title: 'Native Features',
        titleAr: 'ميزات أصلية',
        description: 'Access camera, location, notifications, and more',
        descriptionAr: 'الوصول للكاميرا والموقع والإشعارات والمزيد',
        lessons: [
            {
                id: 'mobile-m3-l1',
                moduleId: 'mobile-m3',
                lessonNumber: 1,
                title: 'Camera & Media',
                titleAr: 'الكاميرا والوسائط',
                description: 'Take photos and access the gallery',
                descriptionAr: 'التقط صوراً والوصول للمعرض',
                videoUrl: '',
                videoDuration: 1200,
            },
            {
                id: 'mobile-m3-l2',
                moduleId: 'mobile-m3',
                lessonNumber: 2,
                title: 'Location Services',
                titleAr: 'خدمات الموقع',
                description: 'Build location-aware apps',
                descriptionAr: 'ابنِ تطبيقات تعرف الموقع',
                videoUrl: '',
                videoDuration: 900,
            },
            {
                id: 'mobile-m3-l3',
                moduleId: 'mobile-m3',
                lessonNumber: 3,
                title: 'Push Notifications',
                titleAr: 'الإشعارات الفورية',
                description: 'Keep users engaged with notifications',
                descriptionAr: 'أبقِ المستخدمين متفاعلين مع الإشعارات',
                videoUrl: '',
                videoDuration: 1200,
                challenge: {
                    id: 'c5',
                    title: 'Location Reminder App',
                    description: 'Build an app that reminds you of tasks when you arrive at a location',
                },
            },
        ],
    },
    {
        id: 'mobile-m4',
        courseType: 'mobile',
        moduleNumber: 4,
        title: 'Publishing Your App',
        titleAr: 'نشر تطبيقك',
        description: 'Get your app on the App Store and Google Play',
        descriptionAr: 'احصل على تطبيقك في App Store و Google Play',
        lessons: [
            {
                id: 'mobile-m4-l1',
                moduleId: 'mobile-m4',
                lessonNumber: 1,
                title: 'Preparing for Release',
                titleAr: 'التحضير للإطلاق',
                description: 'Icons, screenshots, and app store requirements',
                descriptionAr: 'الأيقونات ولقطات الشاشة ومتطلبات المتجر',
                videoUrl: '',
                videoDuration: 900,
            },
            {
                id: 'mobile-m4-l2',
                moduleId: 'mobile-m4',
                lessonNumber: 2,
                title: 'Publishing to Google Play',
                titleAr: 'النشر على Google Play',
                description: 'Step-by-step Android release guide',
                descriptionAr: 'دليل إطلاق Android خطوة بخطوة',
                videoUrl: '',
                videoDuration: 1200,
            },
            {
                id: 'mobile-m4-l3',
                moduleId: 'mobile-m4',
                lessonNumber: 3,
                title: 'Publishing to App Store',
                titleAr: 'النشر على App Store',
                description: 'Step-by-step iOS release guide',
                descriptionAr: 'دليل إطلاق iOS خطوة بخطوة',
                videoUrl: '',
                videoDuration: 1200,
            },
        ],
    },
];

// Helper to get all modules for a course type
export const getModulesForCourse = (courseType: CourseType): CourseModule[] => {
    if (courseType === 'web') return WEB_COURSE_MODULES;
    if (courseType === 'mobile') return MOBILE_COURSE_MODULES;
    if (courseType === 'bundle') return [...WEB_COURSE_MODULES, ...MOBILE_COURSE_MODULES];
    return [];
};

// Get total lessons count for a course
export const getTotalLessons = (courseType: CourseType): number => {
    return getModulesForCourse(courseType).reduce(
        (total, module) => total + module.lessons.length,
        0
    );
};
